version: 0.0.{build}
skip_tags: true
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: nuget restore arvan-proxy.sln
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
test: off
